# Information service url and credentials
information_service_host: localhost
information_service_port: 11200
information_service_login: myuser
information_service_password: mypassword
# MongoDB instance settings
db_instance_port: 30000
db_instance_dbpath: ./../../scalarm_db_data
db_instance_logpath: ./../../log/scalarm_db.log
# MongoDB configsrv settings
db_configsrv_port: 28000
db_configsrv_dbpath: ./../../scalarm_db_config_data
db_configsrv_logpath: ./../../log/scalarm_db_config.log
# MongoDB router settings
db_router_port: 27017
db_router_logpath: ./../../log/scalarm_db_router.log
